meta:
  preview_image: space-500.png
  domainroot: http://thespaceparty.org
  title: The Space Party
  description: "A US political party dedicated to the peaceful exploration of space
    in the name of all humankind, which believes in setting huge goals for all
    humanity to work for, and truly making everyone free to live their lives as they will."
  keywords: "political, party, united states, usa, socialist-libertarian,
    science, health, environment, climate change, racial justice,
    anti-colonialist, feminist, anti-racist, anti-capitalist, anti-war,
    universal health care, marriage equality, non-conforming, platypus,
    space exploration, global family, equality, scientific advancement,
    dignity, peace, greatness, cosmos, higher pursuits"
  fb_app_id: 488284401293167

footer:
 - text: home
   icon: home
   href: /
 - text: coactivate
   icon: widget
   href: http://www.coactivate.org/projects/spaceparty
 - text: twitter
   icon: social-twitter
   href: https://twitter.com/SpacePartyUSA
 - text: facebook
   icon: social-facebook
   href: https://facebook.com/SpacePartyUSA
 - text: blog
   icon: pencil
   href: http://www.coactivate.org/projects/spaceparty/blog/
 - text: wiki
   icon: database
   href: http://www.coactivate.org/projects/spaceparty/project-home
 - text: privacy
   icon: lock
   href: /privacy.html
 - text: github
   icon: social-github
   href: https://github.com/spaceparty/space-party-website/
